apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
    labels: 
      app: grafana
spec:
    replicas: 1
    selector:
      matchLabels:
        tier: monitor 
        app: grafana
    template:
      metadata:
        labels:
          tier: monitor
          app: grafana
      spec:
        containers:
        - name: grafana-container
          image: grafana/grafana:latest

          ports:
          - containerPort: 3000

          volumeMounts:
          - name: grafana-volume
            mountPath: /var/lib/grafana

        volumes:
        - name: grafana-volume
          persistentVolumeClaim:
           claimName: pvc-grafana