apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: prom
      tier: monitor
  template:
    metadata:
      labels:
        tier: monitor
        app: prom
    spec:
      containers:
      - name: prom
        image: prom/prometheus

        ports:
        - containerPort: 9090

        volumeMounts:
        - name: prometheus-volume
          mountPath: /data
      volumes:
      - name: prometheus-volume
        persistentVolumeClaim:
            claimName: pvc-prom