apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  labels:
    app: prom
spec:
  selector:
    app: prom
  type: NodePort
  ports:
  - nodePort: 30001
    port: 9090
    targetPort: 9090
    name: prometheus-port
